Optimise s3cmd puppet module
RewardGateway/capriza-s3cmd pull request #1
Opened 2016-11-18 12:55 UTC by nikkonix

2016-11-22 14:41 UTC, Vincent-- requested changes

2016-11-22 14:41 UTC, Vincent-- commented on manifests/commands/get.pp
> +    $testvar = $name
Do we need this testvar variable?

2016-11-22 14:41 UTC, Vincent-- commented on manifests/config.pp
> +        default => '/home/$owner',
Shouldn't that use double quotes?

2016-11-22 14:41 UTC, Vincent-- commented on manifests/install.pp
> -  if $osfamily == 'redhat' {
Why did you remove the part of the code related to the osfamily?

2016-11-22 15:41 UTC, nikkonix commented on manifests/commands/get.pp
> +    $testvar = $name
I tested and forgot this variable. Fixed.

2016-11-22 15:42 UTC, nikkonix commented on manifests/config.pp
> +        default => '/home/$owner',
Fixed.

2016-11-22 15:43 UTC, nikkonix commented on manifests/install.pp
> -  if $osfamily == 'redhat' {
I removed in the beginning, before this conversation in which we discuss that this module wont service only to us and one day we can request PR to the origin. Restored.

2016-11-28 14:19 UTC, Vincent-- approved these changes

2016-11-28 14:20 UTC, merged